#! /usr/bin/python
# -*- coding:utf-8 -*-
# notificador-mostrar V2.0
# Author: Matias Basso <mbasso@plan.ceibal.edu.uy>
#----------------------------------------------------------------------
# Muestra los mensajes vigentes dentro de la Base de Datos para Gnome.
#----------------------------------------------------------------------
import sys
import os
    
(prev,curr) = os.path.split(os.path.dirname(os.path.abspath(__file__)))

# Si estoy en ambiente de testing, importo ceibal desde alli
if os.path.isfile(os.path.join(prev, '/testing_env')):
    sys.path.append(prev)
    
import ceibal

try:
    import gtk
    import webkit
    from ceibal.notifier.viewer_gtk2 import *
except:
    from ceibal.notifier.viewer_gtk3 import *

win = VentanaBoton()
