#! /usr/bin/python
# -*- coding:utf-8 -*-
# notificador-mostrar V2.0
# Author: Matias Basso <mbasso@plan.ceibal.edu.uy>
#----------------------------------------------------------------------
# Muestra los mensajes vigentes dentro de la Base de Datos para Gnome.
#----------------------------------------------------------------------
import sys
import os

(prev,curr) = os.path.split(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(prev)

from ceibal.notifier.viewer import *



win = VentanaBoton()

