#! /usr/bin/python
# -*- coding:utf-8 -*-
# notificador-mostrar V2.0
# Author: Matias Basso <mbasso@plan.ceibal.edu.uy>
#----------------------------------------------------------------------
# Muestra los mensajes vigentes dentro de la Base de Datos para Gnome.
#----------------------------------------------------------------------
import sys
import os

try:
    from gi.repository import Gtk
    from ceibal.notifier.viewer_gtk3 import *
except:
    from ceibal.notifier.viewer_gtk2 import *

win = VentanaBoton()
